#!/bin/sh
# Phase H Bootstrap env upsert (POSIX sh)
# 用法: sh scripts/patch-smart-money-phase-h-bootstrap-env.sh /root/polymarket-backend/.env
set -eu

ENV_FILE="${1:-.env}"
if [ ! -f "$ENV_FILE" ]; then
  echo "ERROR: env file not found: $ENV_FILE" >&2
  exit 1
fi

if command -v sed >/dev/null 2>&1; then
  sed -i 's/\r$//' "$ENV_FILE" 2>/dev/null || true
  sed -i 's/\r$//' "$0" 2>/dev/null || true
fi

STAMP=$(date +%Y%m%d%H%M%S)
BAK="${ENV_FILE}.bak.phase-h-bootstrap.${STAMP}"
cp -a "$ENV_FILE" "$BAK"
echo "backup: $BAK"

upsert() {
  key="$1"
  val="$2"
  if grep -q "^${key}=" "$ENV_FILE"; then
    grep -v "^${key}=" "$ENV_FILE" > "${ENV_FILE}.tmp"
    mv "${ENV_FILE}.tmp" "$ENV_FILE"
  fi
  printf '%s=%s\n' "$key" "$val" >> "$ENV_FILE"
}

upsert SMART_MONEY_DISCOVERY_BOOTSTRAP_BOARD true
upsert SMART_MONEY_DISCOVERY_INGEST_PER_RUN 2500
upsert SMART_MONEY_LEADERBOARD_INGEST_RESERVED_SLOTS 500
upsert SMART_MONEY_BLOCK_SCAN_INGEST_MAX 80
upsert SMART_MONEY_BLOCK_SCAN_MIN_FILLS 8
upsert SMART_MONEY_BLOCK_SCAN_MIN_NOTIONAL_USD 2000
upsert SMART_MONEY_BLOCK_SCAN_FETCH_PRIORITY_SLOTS 4
upsert SMART_MONEY_RAW_BOARD_ACTIVE_CAP 15000
upsert SMART_MONEY_RAW_BLOCKSCAN_ACTIVE_CAP 2000
upsert SMART_MONEY_LIGHT_PRIORITY_BATCH_SLOTS 24
upsert SMART_MONEY_LIGHT_FETCH_BATCH_SIZE 30
upsert SMART_MONEY_LIGHT_FETCH_INTERVAL_MS 90000
upsert SMART_MONEY_ANALYZE_CONCURRENCY 2
upsert SMART_MONEY_L0_DB_ENABLED true
upsert SMART_MONEY_LIGHT_PERSIST_SNAPSHOT false
upsert SMART_MONEY_DEEP_FORCE_LIVE_ON_FIRST_QUALIFIED false
upsert SMART_MONEY_PROFILE_SNAPSHOT_TTL_MS 7200000
upsert SMART_MONEY_COPY_POOL_REFRESH_BATCH_SHARE 0.10
upsert SMART_MONEY_QUALIFIED_FULL_HOLD_MS 21600000
upsert SMART_MONEY_BOARD_BACKLOG_BUMP_MAX 1000
upsert SMART_MONEY_LIGHT_BOOTSTRAP_BOARD_SHARE 0.8
upsert SMART_MONEY_RAW_WEAK_DORMANT_DAYS 30

echo "patched: $ENV_FILE (Phase H Bootstrap)"
grep -E '^(SMART_MONEY_DISCOVERY_BOOTSTRAP_BOARD|SMART_MONEY_L0_DB_ENABLED|SMART_MONEY_DEEP_FORCE_LIVE_ON_FIRST_QUALIFIED|SMART_MONEY_COPY_POOL_REFRESH_BATCH_SHARE|SMART_MONEY_LIGHT_PERSIST_SNAPSHOT|SMART_MONEY_BLOCK_SCAN_INGEST_MAX)=' "$ENV_FILE" || true
