#!/bin/sh
# 搂15 env upsert 鈥?POSIX sh锛堥伩鍏?bash pipefail / CRLF 闂锛?
# 鐢ㄦ硶: sh scripts/patch-smart-money-s15-env.sh /root/polymarket-backend/.env
set -eu

ENV_FILE="${1:-.env}"
if [ ! -f "$ENV_FILE" ]; then
  echo "ERROR: env file not found: $ENV_FILE" >&2
  exit 1
fi

# 鍘绘帀鍙兘娈嬬暀鐨?CRLF
if command -v sed >/dev/null 2>&1; then
  sed -i 's/\r$//' "$ENV_FILE" 2>/dev/null || true
  sed -i 's/\r$//' "$0" 2>/dev/null || true
fi

STAMP=$(date +%Y%m%d%H%M%S)
BAK="${ENV_FILE}.bak.s15.${STAMP}"
cp -a "$ENV_FILE" "$BAK"
echo "backup: $BAK"

upsert() {
  key="$1"
  val="$2"
  if grep -q "^${key}=" "$ENV_FILE"; then
    # 鍒犻櫎鎵€鏈夊悓鍚嶈鍚庤拷鍔犱竴琛岋紝閬垮厤閲嶅
    grep -v "^${key}=" "$ENV_FILE" > "${ENV_FILE}.tmp"
    mv "${ENV_FILE}.tmp" "$ENV_FILE"
  fi
  printf '%s=%s\n' "$key" "$val" >> "$ENV_FILE"
}

upsert SMART_MONEY_TRADER_SCORE_AS_PRIMARY true
upsert SMART_MONEY_COPY_POOL_ENTER_SCORE 50
upsert SMART_MONEY_COPY_POOL_EXIT_SCORE 40
upsert SMART_MONEY_COPY_POOL_EXIT_MISS_COUNT 2
upsert SMART_MONEY_COPY_POOL_REQUIRE_TIER2E false
upsert SMART_MONEY_L1_MAX_DD_LE_RETURN false
upsert SMART_MONEY_L1_MAX_DD_USD_LT_PNL true
upsert SMART_MONEY_L1_REQUIRE_LIFETIME_VOLUME false
upsert SMART_MONEY_L1_REQUIRE_WIN_RATE false
upsert SMART_MONEY_L1_REQUIRE_TOTAL_RETURN false
upsert SMART_MONEY_SCORE_POOL_MIN_PNL_1Y 200
upsert SMART_MONEY_SCORE_POOL_MIN_PROFIT_FACTOR 1.0
upsert SMART_MONEY_SCORE_POOL_MIN_CLOSED_MARKETS 5
upsert SMART_MONEY_SCORE_POOL_MIN_TRADES_30D 2
upsert SMART_MONEY_RANK_MODEL_ENABLED false
upsert SMART_MONEY_ANALYZE_CONCURRENCY 2
upsert SMART_MONEY_TOP_LIMIT 2500
upsert SMART_MONEY_QUALIFIED_MAX_ACTIVE 2500
upsert SMART_MONEY_SCORED_MAX_ACTIVE 600
upsert SMART_MONEY_SCORED_MAX_MISS 1
upsert SMART_MONEY_COPYABILITY_ENRICH_ENABLED true

echo "patched: $ENV_FILE"
echo "---- effective keys ----"
grep -E '^(SMART_MONEY_TRADER_SCORE_AS_PRIMARY|SMART_MONEY_COPY_POOL_ENTER_SCORE|SMART_MONEY_COPY_POOL_EXIT_SCORE|SMART_MONEY_COPY_POOL_EXIT_MISS_COUNT|SMART_MONEY_COPY_POOL_REQUIRE_TIER2E|SMART_MONEY_L1_MAX_DD_LE_RETURN|SMART_MONEY_L1_MAX_DD_USD_LT_PNL|SMART_MONEY_L1_REQUIRE_|SMART_MONEY_SCORE_POOL_MIN_PNL_1Y|SMART_MONEY_SCORE_POOL_MIN_PROFIT_FACTOR|SMART_MONEY_SCORE_POOL_MIN_CLOSED_MARKETS|SMART_MONEY_SCORE_POOL_MIN_TRADES_30D|SMART_MONEY_RANK_MODEL_ENABLED|SMART_MONEY_ANALYZE_CONCURRENCY|SMART_MONEY_TOP_LIMIT|SMART_MONEY_QUALIFIED_MAX_ACTIVE|SMART_MONEY_SCORED_MAX_ACTIVE|SMART_MONEY_SCORED_MAX_MISS|SMART_MONEY_COPYABILITY_ENRICH_ENABLED)=' "$ENV_FILE" || true
